[package]
name = "asr33emu"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "asr33emu"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eframe = { version = "0.36.1", default-features = false, features = [
    "default_fonts",
    "links",
    "wayland",
    "web_screen_reader",
    "wgpu",
    "x11",
] }
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = "1.0"
serialport = { version = "4.9", default-features = false }

[target.'cfg(windows)'.dependencies]
rfd = { version = "0.17.2", default-features = false }
windows-sys = { version = "0.61", features = [
    "Win32_Devices_Communication",
    "Win32_Foundation",
    "Win32_Media_Audio",
] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.23"
